<?php
/**
 * @author Drajat Hasan
 * @email drajathasan20@gmail.com
 * @create date 2022-06-09 10:48:53
 * @modify date 2022-06-09 12:28:12
 * @license MIT
 */

namespace Zein\Hijri;

final class Hijri extends go2hi
{
    /**
     * Language map
     *
     * @var array
     */
    private $langMap = ['id' => 1, 'en' => 0];

    /**
     * Defaulte language
     *
     * @var integer
     */
    private $defaultLang = 1;

    /**
     * Default timestamp
     *
     * @var integer
     */
    private $defaultTimestamp = 0;

    /**
     * Default format
     *
     * @var string
     */
    private $defaultFormat = 'd F Y';

    /**
     * String time list
     * 
     * will generated by ago() and next() method
     *
     * @var array
     */
    private $stringTime = [];
    
    /**
     * Get current date
     *
     * @return void
     */
    public static function now()
    {
        return new static;
    }

    /**
     * Get yesterday
     *
     * @return void
     */
    public static function yesterday()
    {
        $static = new static;
        $static->timestamp('-1 Day');
        return $static;
    }

    /**
     * Get tomorrow
     *
     * @return void
     */
    public static function tomorrow()
    {
        $static = new static;
        $static->timestamp('+1 Day');
        return $static;
    }

    /**
     * How many day?
     *
     * @param integer $day
     * @return void
     */
    public static function get(int $day)
    {
        $static = new static;
        $static->stringTime[] = $day;
        return $static;
    }

    /**
     * Day string format
     *
     * @return void
     */
    public function day()
    {
        $this->stringTime[] = 'day';
        return $this;
    }

    /**
     * Month string format
     *
     * @return void
     */
    public function month()
    {
        $this->stringTime[] = 'month';
        return $this;
    }

    /**
     * Year string format
     *
     * @return void
     */
    public function year()
    {
        $this->stringTime[] = 'year';
        return $this;
    }

    /**
     * Compile string time to get last day
     *
     * @return void
     */
    public function ago()
    {
        $this->timestamp('-' . implode(' ', $this->stringTime));
        return $this;
    }

    /**
     * Compile string time to get next day
     *
     * @return void
     */
    public function next()
    {
        $this->timestamp('+' . implode(' ', $this->stringTime));
        return $this;
    }

    /**
     * Setter for date format
     *
     * @param string $format
     * @return void
     */
    public function format(string $format)
    {
        $this->defaultFormat = $format;
        return $this;
    }

    /**
     * Setter for default lang
     *
     * @param string $langCode
     * @return void
     */
    public function lang(string $langCode)
    {
        $this->defaultLang = $this->langMap[$langCode]??3;
        return $this;
    }

    /**
     * Convert string to unix timestamp
     *
     * @param [type] $timestamp
     * @return void
     */
    public function timestamp($timestamp)
    {
        $this->defaultTimestamp = strtotime($timestamp);
        return $this;
    }

    /**
     * All inputed data will be generated by go2hi :)
     *
     * @return string
     */
    public function __toString()
    {
        return parent::date($this->defaultFormat, 1, $this->defaultTimestamp, $this->defaultLang);
    }
}